[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
user_data_anchor = "8a66WXwRT5Rj9z5eFqoV2NEAm7sv3cKj1VbpF6B72tpS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
